---
- name: TrueHelloWorld
  hosts: test
  tasks:
  - name: Creates directory
    file:
        path: /home/isft/PyHTTP
        state: directory
  - name: Checkout The Code From Github Using Ansible.
    git:
        repo: 'https://github.com/ImSFT/SimplePythonHTTP.git'
        dest: /home/isft/PyHTTP
  - name: Start Web SARVAR
    script: /home/isft/PyHTTP/SimpleHttp.py
    async: 1000
    poll: 0
  - name: test 6669 port
    shell: ss -l | grep 6669
