---
- name: TrueHelloWorld
  hosts: test
  tasks:
  - name: Creates directory
    file:
        path: ~/PyHTTP
        state: directory
  - name: Checkout The Code From Github Using Ansible.
    git:
        repo: 'https://github.com/ImSFT/SimplePythonHTTP.git'
        dest: ~/PyHTTP
  - name: Start Web SARVAR
    command: python3 ~/PyHTTP/SimpleHttp.py
    async: 45
    poll: 5
  - name: test WebSARVAR
    command: ss -l | grep 6669
