---
- name: TrueHelloWorld
  hosts: test
  tasks:
  - name: Creates directory
    file:
        path: /home/isft/PyHTTP
        state: directory
  - name: Checkout The Code From Github Using Ansible.
    git:
        repo: 'https://github.com/ImSFT/SimplePythonHTTP.git'
        dest: /home/isft/PyHTTP
  - name: Start Web SARVAR
    command: /home/isft/PyHTTP/SimpleHttp.py
