---
- name: TrueHelloWorld
  hosts: test
  tasks:
  - name: Hello Message
    debug:
        msg: "Hello World!"
  - name: Creates directory
    file:
        path: /home/isft/PyHTTP
        state: directory
  - git:
        repo: ssh://git@github.com:ImSFT/SimplePythonHTTP.git
        dest: /home/isft/PyHTTP
  - name: Start Web SARVAR
    script: /home/isft/PyHTTP/SimpleHttp.py
